# Generated by Django 3.1.6 on 2021-02-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztp', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'permissions': (('list_config', 'Can list config'),)},
        ),
        migrations.AlterModelOptions(
            name='firmware',
            options={'permissions': (('list_firmware', 'Can list firmware'),)},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'permissions': (('list_platform', 'Can list platform'),)},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'permissions': (('list_vendor', 'Can list vendor'),)},
        ),
        migrations.AlterModelOptions(
            name='ztpscript',
            options={'permissions': (('list_ztpscript', 'Can list ztp script'),)},
        ),
    ]
