# Generated by Django 3.1.7 on 2021-02-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztp', '0004_initial_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='configparameter',
            name='is_mandatory',
            field=models.BooleanField(default=True, verbose_name='mandatory parameter'),
        ),
    ]
