# Generated by Django 3.1.6 on 2021-02-19 16:32

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztp', '0004_initial_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'permissions': (('list_vendor', 'Can list vendor'),), 'verbose_name': 'vendor'},
        ),
        migrations.AlterField(
            model_name='config',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z._-]+$', 'Only alphanumeric characters, dot ".", underscore "_", and hyphen "-" symbols are allowed.')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='config',
            name='template',
            field=models.TextField(verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='configparameter',
            name='data',
            field=models.TextField(blank=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='configparameter',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z_][0-9a-zA-Z._-]*$', 'Only alphanumeric characters, dot ".", underscore "_", and hyphen "-" symbols are allowed.')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='firmwares/', location='firmwares/'), unique=True, upload_to='', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='filesize',
            field=models.IntegerField(verbose_name='filesize'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='md5_hash',
            field=models.CharField(max_length=32, verbose_name='MD5 hash'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='sha512_hash',
            field=models.CharField(max_length=128, verbose_name='SHA512 hash'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ztpparameter',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z_][0-9a-zA-Z._-]*$', 'Only alphanumeric characters, dot ".", underscore "_", and hyphen "-" symbols are allowed.')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ztpparameter',
            name='value',
            field=models.CharField(blank=True, max_length=200, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='ztpscript',
            name='accept_query_string',
            field=models.BooleanField(default=False, verbose_name='accept_query_string'),
        ),
        migrations.AlterField(
            model_name='ztpscript',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='ztpscript',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z._-]+$', 'Only alphanumeric characters, dot ".", underscore "_", and hyphen "-" symbols are allowed.')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ztpscript',
            name='priority_query_string_over_arguments',
            field=models.BooleanField(default=False, verbose_name='priority query string over arguments'),
        ),
        migrations.AlterField(
            model_name='ztpscript',
            name='render_template',
            field=models.BooleanField(default=True, verbose_name='render template'),
        ),
        migrations.AlterField(
            model_name='ztpscript',
            name='template',
            field=models.TextField(verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='ztpscript',
            name='use_parameters',
            field=models.BooleanField(default=True, verbose_name='use parameters'),
        ),
    ]
