# Generated by Django 3.1.7 on 2021-03-06 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ztp', '0005_configparameter_is_mandatory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'permissions': (('list_config', 'Can list config'),), 'verbose_name': 'Configuration', 'verbose_name_plural': 'Configurations'},
        ),
        migrations.AlterModelOptions(
            name='configparameter',
            options={'verbose_name': "Configuration's parameter", 'verbose_name_plural': "Configuration's parameters"},
        ),
        migrations.AlterModelOptions(
            name='firmware',
            options={'permissions': (('list_firmware', 'Can list firmware'),), 'verbose_name': 'Firmware', 'verbose_name_plural': 'Firmwares'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'permissions': (('list_platform', 'Can list platform'),), 'verbose_name': 'Platform', 'verbose_name_plural': 'Platforms'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'permissions': (('list_vendor', 'Can list vendor'),), 'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.AlterModelOptions(
            name='ztpparameter',
            options={'verbose_name': "ZTP script's parameter", 'verbose_name_plural': "ZTP script's parameters"},
        ),
        migrations.AlterModelOptions(
            name='ztpscript',
            options={'permissions': (('list_ztpscript', 'Can list ztp script'),), 'verbose_name': 'ZTP script', 'verbose_name_plural': 'ZTP scripts'},
        ),
        migrations.RemoveField(
            model_name='firmware',
            name='platform',
        ),
        migrations.AddField(
            model_name='config',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='config',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configparameter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configparameter',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configparameter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firmware',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmware',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='firmware',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ztpparameter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ztpparameter',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ztpparameter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ztpscript',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ztpscript',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ztpscript',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlatformFirmwareSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(null=True)),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ztp.firmware')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ztp.platform')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='firmware',
            name='platforms',
            field=models.ManyToManyField(related_name='firmwares', through='ztp.PlatformFirmwareSupport', to='ztp.Platform', verbose_name='supported platforms'),
        ),
        migrations.AddConstraint(
            model_name='platformfirmwaresupport',
            constraint=models.UniqueConstraint(fields=('platform', 'is_default'), name='unique default firmware'),
        ),
    ]
