# Generated by Django 3.1.7 on 2021-03-14 17:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztp', '0007_add_logs_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='language',
            field=models.CharField(blank=True, choices=[('clike', 'C-like (C, C++, C#, Java, Kotlin, ...)'), ('go', 'Go'), ('javascript', 'Javascript'), ('perl', 'Perl'), ('php', 'PHP'), ('python', 'Python'), ('ruby', 'Ruby'), ('rust', 'Rust'), ('tcl', 'Tcl'), ('xml', 'XML'), ('yaml', 'YAML')], max_length=15, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='ztpscript',
            name='language',
            field=models.CharField(blank=True, choices=[('clike', 'C-like (C, C++, C#, Java, Kotlin, ...)'), ('go', 'Go'), ('javascript', 'Javascript'), ('perl', 'Perl'), ('php', 'PHP'), ('python', 'Python'), ('ruby', 'Ruby'), ('rust', 'Rust'), ('tcl', 'Tcl'), ('xml', 'XML'), ('yaml', 'YAML')], max_length=15, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='config',
            name='template',
            field=models.TextField(blank=True, verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/firmwares/', location='firmwares/'), unique=True, upload_to='', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='firmwares', through='ztp.PlatformFirmwareSupport', to='ztp.Platform', verbose_name='supported platforms'),
        ),
        migrations.AlterField(
            model_name='ztpscript',
            name='template',
            field=models.TextField(blank=True, verbose_name='template'),
        ),
    ]
