# Generated by Django 3.1.7 on 2021-03-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztp', '0008_auto_20210314_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='language',
        ),
        migrations.RemoveField(
            model_name='ztpscript',
            name='language',
        ),
    ]
