# Generated by Django 3.1.7 on 2021-03-03 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('severity', models.PositiveSmallIntegerField(choices=[(0, 'EMERGENCY'), (1, 'ALERT'), (2, 'CRITICAL'), (3, 'ERROR'), (4, 'WARNING'), (5, 'NOTICE'), (6, 'INFO'), (7, 'DEBUG')], default=6, verbose_name='severity')),
                ('location', models.PositiveSmallIntegerField(choices=[(0, 'local'), (1, 'remote')], default=0, verbose_name='location')),
                ('task_type', models.PositiveSmallIntegerField(choices=[(0, 'admin'), (1, 'operation'), (2, 'debugging')], default=1, verbose_name='task type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, verbose_name='meta-data')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log',
                'permissions': (('list_log', 'Can list logs'), ('view_log', 'Can view logs')),
            },
        ),
    ]
